import Head from 'next/head'
import {Inter} from '@next/font/google'
import Hero from '@/components/layout/HeroSection'
import Feature from '@/components/layout/Feature'

// #TODO

// const inter = Inter({subsets: ['latin']})

export default function Home() {
  return (
    <>
      <Head>
        <title>E-Commerce Application | Fullstack</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Feature />
    </>
  )
}
// Home.getLayout = function getLayout(page: ReactElement) {
//   return (
//     <MainLayout>
//       <>{page}</>
//     </MainLayout>
//   )
// }
